# Generated by Django 6.0.5 on 2026-05-14 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_userprofile_profile_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='phone',
            new_name='photo',
        ),
    ]
